<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">	
</head>
<body>
<?php if(isset($this->special)) {?>
<pre>
<?php 
print_r($this->special);
?>
</pre>
<?php }?>
<ul>
	<li><a href="<?php echo $this->uri('/author/list')?>"><?php echo $this->_('Authors')?></a></li>
	<li><a href="<?php echo $this->uri('/book/list')?>"><?php echo $this->_('Books')?></a></li>
	<li><a href="<?php echo $this->uri('/store/list')?>"><?php echo $this->_('Stores')?></a></li>
</ul>